name: Practice
version: ${project.version}
main: fr.xenover.practice.Practice
api-version: 1.16
authors: [ XenoverONE ]
commands:
  duel:
    description: Pour gerer les combats dans le serveur
  elo:
    description: Pour voir l'elo d'un joueur
